/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Usuário
 */
public class ViewMenu extends javax.swing.JFrame {
        private String usuarioAutenticado;
        
        public String getusuarioAutenticado(){
            return usuarioAutenticado;
        }
    /**
     * Creates new form ViewMenu
     */
    public ViewMenu() {
        Login login = new Login(null,true);
        login.setVisible(true);
        usuarioAutenticado = login.getUsuarioAutenticado();
        if(!usuarioAutenticado.equals("")){
        initComponents();
        lblUsuarioAutenticado.setText("Usuário: " + usuarioAutenticado);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblUsuarioAutenticado = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        usuario = new javax.swing.JMenu();
        cadastro = new javax.swing.JMenu();
        trocarSenha = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        txtSaldo = new javax.swing.JMenuItem();
        txtSair = new javax.swing.JMenuItem();
        financas = new javax.swing.JMenu();
        txtGerarRelatorio = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuItemInserirCategoria = new javax.swing.JMenuItem();
        ajuda = new javax.swing.JMenu();
        ajudaSobre = new javax.swing.JMenuItem();
        ajudaVersao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.add(filler1);

        lblUsuarioAutenticado.setText("Usuário:");
        jToolBar1.add(lblUsuarioAutenticado);
        jToolBar1.add(filler3);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        usuario.setText("Usuário");

        cadastro.setText("Meu Cadastro");

        trocarSenha.setText("Trocar/Esqueci a senha");
        trocarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocarSenhaActionPerformed(evt);
            }
        });
        cadastro.add(trocarSenha);

        jMenuItem1.setText("Meu dados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        cadastro.add(jMenuItem1);

        usuario.add(cadastro);

        txtSaldo.setText("Saldo");
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });
        usuario.add(txtSaldo);

        txtSair.setText("Sair");
        txtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSairActionPerformed(evt);
            }
        });
        usuario.add(txtSair);

        jMenuBar1.add(usuario);

        financas.setText("Lançamentos");

        txtGerarRelatorio.setText("Ver contas");
        txtGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGerarRelatorioActionPerformed(evt);
            }
        });
        financas.add(txtGerarRelatorio);

        jMenuItem3.setText("Inserir contas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        financas.add(jMenuItem3);

        jMenuBar1.add(financas);

        jMenu2.setText("Categorias");

        jMenuItem2.setText("Ver categorias");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        MenuItemInserirCategoria.setText("Inserir categorias");
        MenuItemInserirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemInserirCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemInserirCategoria);

        jMenuBar1.add(jMenu2);

        ajuda.setText("Ajuda");

        ajudaSobre.setText("Sobre");
        ajuda.add(ajudaSobre);

        ajudaVersao.setText("Versão");
        ajuda.add(ajudaVersao);

        jMenuBar1.add(ajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(JOptionPane.showConfirmDialog(this, "Deseja realmente sair?","Atenção",JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION){
            setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        }else{
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void MenuItemInserirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemInserirCategoriaActionPerformed
        InserirCategoria tela = InserirCategoria.getInstance();
        tela.pack();
        if(!tela.isVisible()){
            jDesktopPane1.add(tela);
            tela.setVisible(true);
        }else
        tela.moveToFront();
    }//GEN-LAST:event_MenuItemInserirCategoriaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        VerCategorias tela = VerCategorias.getInstance();
        tela.pack();
        if(!tela.isVisible()){
            jDesktopPane1.add(tela);
            tela.setVisible(true);
        }else
        tela.moveToFront();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSairActionPerformed
        WindowEvent winEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winEvent);
    }//GEN-LAST:event_txtSairActionPerformed

    private void trocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocarSenhaActionPerformed
        TrocarSenha tela = new TrocarSenha();
        tela.setVisible(true);
    }//GEN-LAST:event_trocarSenhaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        InserirConta tela = InserirConta.getInstance();
        tela.pack();
        if(!tela.isVisible()){
            jDesktopPane1.add(tela);
            tela.setVisible(true);
        }else
        tela.moveToFront();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void txtGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGerarRelatorioActionPerformed
        // TODO add your handling code here:
        VerContas tela = VerContas.getInstance();
        tela.pack();
        if(!tela.isVisible()){
            jDesktopPane1.add(tela);
            tela.setVisible(true);
        }else
        tela.moveToFront();
    }//GEN-LAST:event_txtGerarRelatorioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ViewPerfil tela = ViewPerfil.getInstance();
        tela.pack();
        if(!tela.isVisible()){
            jDesktopPane1.add(tela);
            tela.setVisible(true);
        }else
        tela.moveToFront();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
        ViewSaldo tela = ViewSaldo.getInstance();
        tela.pack();
        if(!tela.isVisible()){
            jDesktopPane1.add(tela);
            tela.setVisible(true);
        }else
        tela.moveToFront();
    }//GEN-LAST:event_txtSaldoActionPerformed

    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemInserirCategoria;
    private javax.swing.JMenu ajuda;
    private javax.swing.JMenuItem ajudaSobre;
    private javax.swing.JMenuItem ajudaVersao;
    private javax.swing.JMenu cadastro;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JMenu financas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblUsuarioAutenticado;
    private javax.swing.JMenuItem trocarSenha;
    private javax.swing.JMenuItem txtGerarRelatorio;
    private javax.swing.JMenuItem txtSair;
    private javax.swing.JMenuItem txtSaldo;
    private javax.swing.JMenu usuario;
    // End of variables declaration//GEN-END:variables
}
