/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Usuário
 */
public class ViewMenu extends javax.swing.JFrame {
        private String usuarioAutenticado;
        
        public String getusuarioAutenticado(){
            return usuarioAutenticado;
        }
    /**
     * Creates new form ViewMenu
     */
    public ViewMenu() {
        Login login = new Login(null,true);
        login.setVisible(true);
        usuarioAutenticado = login.getUsuarioAutenticado();
        if(!usuarioAutenticado.equals("")){
        initComponents();
        lblUsuarioAutenticado.setText("Usuário: " + usuarioAutenticado);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblUsuarioAutenticado = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        usuario = new javax.swing.JMenu();
        cadastro = new javax.swing.JMenu();
        txtCadastro = new javax.swing.JMenuItem();
        trocarSenha = new javax.swing.JMenuItem();
        txtSaldo = new javax.swing.JMenuItem();
        txtSair = new javax.swing.JMenuItem();
        financas = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        txtValoraReceber = new javax.swing.JMenuItem();
        txtContasaPagar = new javax.swing.JMenuItem();
        txtGerarRelatorio = new javax.swing.JMenuItem();
        ajuda = new javax.swing.JMenu();
        ajudaSobre = new javax.swing.JMenuItem();
        ajudaVersao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.add(filler1);

        lblUsuarioAutenticado.setText("Usuário:");
        jToolBar1.add(lblUsuarioAutenticado);
        jToolBar1.add(filler3);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        usuario.setText("Usuário");

        cadastro.setText("Cadastro");

        txtCadastro.setText("Criar novo cadastro");
        txtCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        cadastro.add(txtCadastro);

        trocarSenha.setText("Trocar/Esqueci a senha");
        trocarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocarSenhaActionPerformed(evt);
            }
        });
        cadastro.add(trocarSenha);

        usuario.add(cadastro);

        txtSaldo.setText("Saldo");
        usuario.add(txtSaldo);

        txtSair.setText("Sair");
        txtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSairActionPerformed(evt);
            }
        });
        usuario.add(txtSair);

        jMenuBar1.add(usuario);

        financas.setText("Lançamentos");

        jMenu1.setText("Inserir valores");

        txtValoraReceber.setText("Valor a receber");
        jMenu1.add(txtValoraReceber);

        txtContasaPagar.setText("Contas a pagar");
        txtContasaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContasaPagarActionPerformed(evt);
            }
        });
        jMenu1.add(txtContasaPagar);

        financas.add(jMenu1);

        txtGerarRelatorio.setText("Gerar relatório");
        financas.add(txtGerarRelatorio);

        jMenuBar1.add(financas);

        ajuda.setText("Ajuda");

        ajudaSobre.setText("Sobre");
        ajuda.add(ajudaSobre);

        ajudaVersao.setText("Versão");
        ajuda.add(ajudaVersao);

        jMenuBar1.add(ajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void trocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocarSenhaActionPerformed
        TrocarSenha tela = new TrocarSenha();
        tela.setVisible(true);
    }//GEN-LAST:event_trocarSenhaActionPerformed

    private void txtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSairActionPerformed
       WindowEvent winEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winEvent);
    }//GEN-LAST:event_txtSairActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        ViewCadastro tela = new ViewCadastro();
        tela.setVisible(true);
      
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(JOptionPane.showConfirmDialog(this, "Deseja realmente sair?","Atenção",JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION){
            setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        }else{
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtContasaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContasaPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContasaPagarActionPerformed

    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajuda;
    private javax.swing.JMenuItem ajudaSobre;
    private javax.swing.JMenuItem ajudaVersao;
    private javax.swing.JMenu cadastro;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JMenu financas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblUsuarioAutenticado;
    private javax.swing.JMenuItem trocarSenha;
    private javax.swing.JMenuItem txtCadastro;
    private javax.swing.JMenuItem txtContasaPagar;
    private javax.swing.JMenuItem txtGerarRelatorio;
    private javax.swing.JMenuItem txtSair;
    private javax.swing.JMenuItem txtSaldo;
    private javax.swing.JMenuItem txtValoraReceber;
    private javax.swing.JMenu usuario;
    // End of variables declaration//GEN-END:variables
}
